### ISSUE TITLE
add this to astroconda?

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/jwst_backgrounds#1]
Nice tool! 

We should probably add this to astroconda as another option for installation in addition to pip. That would be a trivial pull request to astroconda (instructions at https://astroconda.readthedocs.io/en/latest/contributing.html#adding-a-recipe-to-astroconda-contrib). I would be happy to do that if you'd like.

**Comment by pontoppi** [comment]
@mperrin Would be great to get this into astroconda, so if you have the time, please go ahead. Thanks!

**Comment by mperrin** [comment]
Will do. It would probably help if you could make a release here on GitHub, or at least make up a release version number I can use for this when adding it to astroconda

**Comment by pontoppi** [comment]
The release version is 1.1.1. I just created a github release, matching the pypi release.

**Comment by mperrin** [comment]
Hmm, this turns out to be slightly more complicated than I had expected, since this depends on healpy which is not already in astroconda. So I have to either also package that, or figure out how to have a dependency on the healpy package in the condo-forge channel. I'll figure it out but it'll take longer than the 5 minutes I had expected.

**Comment by pontoppi** [comment]
An interesting related issue that we just discovered at the workshop  - looks like the healpy installer might be broken in high sierra, and I wonder if astroconda could help. I think we should go try to recruit some astroconda resources for this. WMO would likely support that.

**Comment by sosey** [comment]
closing this older issue since astroconda is no longer maintained
